version: '3.8'

volumes:
  postgresql-mlflow-data:
  mlflow-artifact-store:

x-app-template: &APP_TEMPLATE  # variable should start with x
    user: "${USER_ID:-1000}"   # environment variable uid
    hostname: "${HOST:-Rahul}" # hostname of the container
    image: project-model   # image to be called
    build:
      context : .
      dockerfile : ./docker/Dockerfile # where is the docker file
      args:
        USER_NAME : "${USER_NAME:-rahulsm.27}"
        USER_ID : "${USER_ID:-1000}"
    env_file:
      - .envs/.postgres
      - .envs/.mlflow-common
      - .envs/.mlflow-dev
      
    volumes : 
      - ./:/app/
      - mlflow-artifact-store:/mlflow-artifact-store
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ipc : host
    init : true


services:
  mlflow-db:
    container_name : mlflow-backend-store
    image: postgres:14
    env_file:
      - .envs/.mlflow-common
      - .envs/.mlflow-dev
      - .envs/.postgres 
    volumes:
      - postgresql-mlflow-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    profiles:
      - dev
  #proflies helps to select services to run like dev related or prod related
  app-dev: # for local processing
    <<: *APP_TEMPLATE
    container_name : project-model-dev-container
    ports :
      - 8080:8080
      
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    profiles:
      - dev
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count : all 
    #           capabilities : [gpu]

  app-prod: # for distributed processing on cloud
    <<: *APP_TEMPLATE
    container_name : project-model-prod-container
    env_file:
      - .envs/.mlflow-common
      - .envs/.mlflow-prod
      - .envs/.infrastructure  
    ports :
      - ${PROD_MLFLOW_SERVER_PORT}:${PROD_MLFLOW_SERVER_PORT}
    profiles:
      - prod
    
  app-ci:
    <<: *APP_TEMPLATE
    container_name : project-model-ci-container
    ports:
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    profiles:
      - ci
